name: Arvados Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  workbench2:
    name: Workbench2 Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build wb2 test container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "services/workbench2/docker/Dockerfile"
          tags: workbench2-test:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: Run wb2 integration tests
        uses: addnab/docker-run-action@v3
        with:
          image: workbench2-test:latest
          options: -v ${{github.workspace}}:/usr/src/arvados -w /usr/src/arvados/services/workbench2
          run: |
            yarn install
            yarn test --no-watchAll --bail --ci || exit $?
            tools/run-integration-tests.sh -a /usr/src/arvados
