# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

name: Arvados Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  workbench2:
    name: Workbench2 Tests
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          # true = remove
          # false = keep
          # this might remove tools that are actually needed, (Node, Go, Python, Ruby, ...)
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          # Cleaning up images causes some failure with the docker build/tests
          docker-images: false
          # Keep swap to avoid thrashing unless we really need the space
          swap-storage: false
      - name: Install pipx and dependencies
        run: |
          sudo apt update
          sudo apt install -y pipx install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Ansible
        run: tools/ansible/install-ansible.sh
      - name: Run unit and integration tests
        run: echo $PWD && cd services/workbench2 && make test
